Repository AbGuthrie/goquery, pull requests merged in 2020-01, with the labels that each got.

#119 Allow hosts to be connected by query string other than UUID
  commands/connect.go
Labels: enhancement, external

#124 Fix go mod and import paths for v2 release
  README.md
  api/mock/client.go
  api/osctrl/client.go
  commands/alias.go
  commands/change_directory.go
  commands/clear.go
  commands/command_map.go
  commands/connect.go
  commands/disconnect.go
  commands/exit.go
  commands/help.go
  commands/history.go
  commands/list_directory.go
  commands/mode.go
  commands/print_hosts.go
  commands/query.go
  commands/resume.go
  commands/schedule.go
  examples/mock.go
  examples/mock_external.go
  go.mod
  go.sum
  goquery.go
  models/api.go
  utils/printer.go
  utils/scheduleQueryAndWait.go
  utils/utils.go
Labels: bug

#125 Fix alias descriptions
  goquery.go
Labels: UX, bug
